name: Deploy Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit google-cloud-speech openai wave

    - name: Create requirements.txt
      run: pip freeze > requirements.txt

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > google_credentials.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=google_credentials.json" >> $GITHUB_ENV

    - name: Set up OpenAI API key
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

    - name: Deploy to Streamlit Cloud
      uses: streamlit/streamlit-deploy-action@v1
      with:
        app-name: your-app-name-here
        streamlit-api-key: ${{ secrets.STREAMLIT_API_KEY }}
