name: Streamlit App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies and tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg python3-distutils

    - name: Create Google credentials file
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > google_credentials.json

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run Streamlit app
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: google_credentials.json
      run: |
        streamlit run main0904.py --server.port 8501 --server.headless true
